export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_ERR = 'LOGIN_ERR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const SKIPPED_LOGIN = 'SKIPPED_LOGIN';
export const ADDRESS_SELECTED = 'ADDRESS_SELECTED';
export const RE_LOGIN = 'RE_LOGIN';


export const GET_USER_ADDRESSES = 'GET_USER_ADDRESSES';
export const USER_ADDRESSES_LOADING = 'USER_ADDRESSES_LOADING';
export const USER_ADDRESSES_FAILED = 'USER_ADDRESSES_FAILED';
export const ADD_SELECTED_ADDRESS = 'ADD_SELECTED_ADDRESS';

export const USERDATA_LOADING = 'USERDATA_LOADING';
export const USERDATA_ERR = 'USERDATA_ERR';
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS';
